### ISSUE TITLE
Error when trying to run image using Dockerfile

### ISSUE THREAD

**Issue by misilot** [UCDavisLibrary/selfcheckout#1]
Hello, I am trying to use this but when running the application after building the image with the included dockerfile.

```
selfcheckout_1  |
selfcheckout_1  | > @ucd-lib/selfcheckout@1.0.0 start /usr/src/app
selfcheckout_1  | > nodemon src/index.js --exec babel-node
selfcheckout_1  |
selfcheckout_1  | [nodemon] 1.18.1
selfcheckout_1  | [nodemon] to restart at any time, enter `rs`
selfcheckout_1  | [nodemon] watching: *.*
selfcheckout_1  | [nodemon] starting `babel-node src/index.js`
selfcheckout_1  | internal/modules/cjs/loader.js:638
selfcheckout_1  |     throw err;
selfcheckout_1  |     ^
selfcheckout_1  |
selfcheckout_1  | Error: Cannot find module '/usr/src/app/src/index.js'
selfcheckout_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
selfcheckout_1  |     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
selfcheckout_1  |     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
selfcheckout_1  |     at Object.<anonymous> (/usr/src/app/node_modules/babel-cli/lib/_babel-node.js:154:22)
selfcheckout_1  |     at Module._compile (internal/modules/cjs/loader.js:778:30)
selfcheckout_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
selfcheckout_1  |     at Module.load (internal/modules/cjs/loader.js:653:32)
selfcheckout_1  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
selfcheckout_1  |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
selfcheckout_1  |     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
selfcheckout_1  | [nodemon] app crashed - waiting for file changes before starting...
```

My example `docker-compose.yml` file:

```yml
version: '3.3'
services:
  selfcheckout:
    build:
      context: .
      dockerfile: Dockerfile
    image: "selfcheckout/selfcheckout:latest"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    ports:
      - "${DOCKER_WEB_PORT_FORWARD:-127.0.0.1:3000}:3000"
    env_file:
      - ./.env
    volumes:
      - ./.env:/usr/src/app/.env
```

Thanks!
